#! /usr/bin/python

import sys
from numpy import load
from scipy.stats import ttest_rel

x = load(sys.argv[1])
y = load(sys.argv[2])

rx = x[:,0] / x[:,1]
ry = y[:,0] / y[:,1]

print rx.mean(), rx.std(), ry.mean(), ry.std()

print ttest_rel(rx, ry)
