# User configuration:

SRCDIR = $(abspath $(dir $(lastword $(MAKEFILE_LIST)))/..)
CONFDIR = $(SRCDIR)/config

#LIBDIR = /usr/local/lib/pyctf
#BINDIR = /usr/local/bin
LIBDIR = $(HOME)/lib/pyctf
BINDIR = $(HOME)/bin

# Compiler and linker
CC = gcc
AR = ar

# Base flags
CFLAGS = -I. -O2 -Wunused -fPIC
LDFLAGS = -lm -lfftw3

# Python venv settings
PYTHON = $(HOME)/Dokumente/Code/NeuroprostheticData/.venv/bin/python
export PYTHON
PYTHON_INCDIR = $(shell $(PYTHON) -c "from sysconfig import get_paths as gp; print(gp()['include'])")
PYTHON_LIBDIR = $(shell $(PYTHON) -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")

CFLAGS += -I$(PYTHON_INCDIR)
LDFLAGS += -L$(PYTHON_LIBDIR) -lpython$(shell $(PYTHON) -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")

CFLAGS = -I. -O2 -Wunused -fPIC
LDFLAGS = -lm -lfftw3

make: all

clean-x:
	for x in $(targets) ; do \
		$(MAKE) -C $$x $@ || exit ;\
	done
	rm -f *~ *.pyc *.o *.a *.so
	rm -fr __pycache__
